// var basket = `$('#basket')`,
//     container = $('#container'),
//     hen = $('.hen'),
//     egg = $('.egg'),
//     egg1 = $('#eggs1'),
//     egg2 = $('#eggs2'),
//     egg3 = $('#egg3'),
//     restart = $('#restart'),
//     score_span = $('#score'),
//     score_1 = $('#score_1'),
//     // life_span = $('#life'),
//     floor = $('#floor'),
//     basket_height = basket.height(),
//     container_height = container.height(),
//     egg_height = eggs.height(),
//     egg_initial_position = parseInt(eggs.css('top')),
//     score = 0,
//     // life = 5,
//     speed = 2,
//     max_speed = 15,
//     counter = 0,
//     score_updated = false,
//     the_gate = 0,
//     anim_id = 0,
//     egg_current_position = 0,
//     egg_top = 0,
//     basket_top = container_height - basket_height,
//     bullseye_num = 0;
var basket = document.getElementById('basket');
var container = document.getElementById('container');
var hen = document.getElementsByClassName('hen');
var egg = document.getElementsByClassName('egg');
var egg1 = document.getElementById('egg1');
var egg2 = document.getElementById('egg2');
var egg3 = document.getElementById('egg3');
var restart = document.getElementById('restart');
var score_span = document.getElementById('score_span');
var score_1 = document.getElementById('score_1');
var floor = document.getElementById('floor');
// var basket_height = basket.height();
// var container_height = container.height();
// var egg_height = eggs.height();
// var egg_initial_position = parseInt(eggs.css('top'));
var score = 0;
var life = 5;
var speed = 2,
    max_speed = 15,
    counter = 0,
    score_updated = false,
    the_gate = 0,
    anim_id = 0,
    egg_current_position = 0,
    egg_top = 0,
    // basket_top = container_height - basket_height,
    bullseye_num = 0;
var life = 5;
var life_span = document.getElementById('life').textContent = life;

